### ISSUE TITLE
Знайти фото Нового Роздолу в Інтернеті

### ISSUE THREAD

**Issue by Viktoria0707** [Viktoria0707/-4#1]
Знайти найкраще фото в інтернеті

**Comment by Viktoria0707** [comment]
Шукаю

**Comment by liliya2323** [comment]
Шукаю вже

**Comment by liliya2323** [comment]
![image](https://user-images.githubusercontent.com/94009261/140989560-d008489f-ba85-4944-bcaa-c52181c344e2.png)

**Comment by liliya2323** [comment]
Зображення знайдено

**Comment by Viktoria0707** [comment]
![unnamed](https://user-images.githubusercontent.com/94007874/140990096-a94144d8-aa7b-445b-8c04-8efc8a36666e.jpg)

**Comment by Viktoria0707** [comment]
фото знайдено
